import ViewDateEndTask from "./ui/create_date_end_task";
import CreateUsersProject from "./ui/create_users_project";
import TabProject from "./ui/tab_project";
import NavbarDetailProject from "./ui/navbar_detail_project";
import ProgressDetailProject from "./ui/progress_detail_project";
import ListTugasDetailProject from "./ui/list_tugas_detail_project";
import ListFileDetailProject from "./ui/list_file_detail_project";
import LiatAnggotaDetailProject from "./ui/list_anggota_detail_project";
import EditTaskProject from "./ui/edit_task_project";
import EditDetailTaskProject from "./ui/edit_detail_task_project";
import ListAnggotaDetailProject from "./ui/list_anggota_detail_project";
import AddDetailTaskProject from "./ui/add_detail_task_project";
import CancelProject from "./ui/cancel_project";
import AddMemberDetailProject from "./ui/add_member_detail_project";
import CreateProject from "./ui/create_project";
import AddFileDetailProject from "./ui/add_file_detail_project";

export { ViewDateEndTask }
export { CreateUsersProject }
export { TabProject }
export { NavbarDetailProject }
export { ProgressDetailProject }
export { ListTugasDetailProject }
export { ListFileDetailProject }
export { ListAnggotaDetailProject }
export { EditTaskProject }
export { EditDetailTaskProject }
export { AddDetailTaskProject }
export { CancelProject }
export { AddMemberDetailProject }
export { CreateProject }
export { AddFileDetailProject }